#!/bin/sh

# exit on error
set -e

# if an argument is provided, change to that directory
[ -n "$1" ] && cd "$1" &> /dev/null

# run a command that will succeed in any git repo and fail elsewhere
git rev-parse &> /dev/null
