#!/bin/sh

# parse args
while [ -n "$1" ]; do
    case "$1" in
        -f|--from)
            shift
            if [ -z "$1" ]; then
                echo Missing from repository
                exit 1
            fi
            from_repo="$1"
            ;;
        *)
            if [ -n "$repo_name" ]; then
                echo Too many arguments
                exit 1
            fi
            repo_name="$1"
            ;;
    esac

    shift
done

# get the repo directory
if ! repo_dir="`repo-name-to-dir "$repo_name"`"; then
    echo Repo name missing or invalid
    exit 1
fi

# make sure the repo doesn't exist yet
if [ -d "$repo_dir" ]; then
    echo Repo already exists
    exit 1
fi

if [ -n "$from_repo" ]; then
    # create the repo from an existing repo
    git clone --mirror "$from_repo" "$repo_dir" \
      && cd "$repo_dir" \
      && git remote remove origin
else
    # create a new repo
    mkdir -p "$repo_dir" \
      && cd "$repo_dir" \
      && git init --bare
fi

if [ "$?" -ne 0 ]; then
    rm -rf "$repo_dir"
fi
